docker support with env variables support
mifi/instauto pull request #84
Opened 2022-03-29 18:16 UTC by maxxxdj

2022-03-31 03:32 UTC, mifi requested changes
Thanks. I left some feedback. I see there's a lot of changes to unrelated files. I think all changes to other files **except** Dockerfile, README.md, docker-compose.yaml and example.js can be removed, am I right?

2022-03-31 03:32 UTC, mifi commented on README.md
> +- We've added a Docker support for insta-auto!
The name of the project is `instauto`, so I'd prefer to keep that name instead of `insta-auto`

2022-03-31 03:32 UTC, mifi commented on example.js
> +  maxFollowsPerHour: process.env.MAX_FOLLOWS_PER_HOUR,
For all these parameters, can we instead default to the old value if environment is not set? Also need to convert most of these to `Number`.
e.g.:
```js
maxFollowsPerHour: process.env.MAX_FOLLOWS_PER_HOUR != null ? parseInt(process.env.MAX_FOLLOWS_PER_HOUR, 10) : 20
```

2022-04-01 04:28 UTC, mifi commented
thanks. I did some additional improvements. I still see that yarn.lock, package.json, index.js changes are part of this PR. I don't think they are needed? If not, could you revert those?

2022-04-01 18:21 UTC, maxxxdj commented
> thanks. I did some additional improvements. I still see that yarn.lock, package.json, index.js changes are part of this PR. I don't think they are needed? If not, could you revert those?

I've tried with the old ones, but Dockerfile was failing to build.
![image](https://user-images.githubusercontent.com/59373264/161320379-294c180a-b750-4dba-adfd-efeac1cfabf0.png)
I suggest to try to run it locally and if it's not a problem to leave them.
Cheers!

2022-04-02 11:30 UTC, mifi commented
That’s odd. Maybe try yarn add instuto instead of npm install instauto

2022-04-03 10:31 UTC, maxxxdj commented
> That’s odd. Maybe try yarn add instuto instead of npm install instauto

It worked! Great, thanks.
The only changes now are some IDE or whitespaces.
I've changed the docker container name to be the correct as your project and product - "instauto".

Cheers

2022-04-03 10:49 UTC, mifi commented
thanks! i would appreciate if you also remove the whitespace changes. after that is solved i think this can be merged

2022-04-03 11:02 UTC, maxxxdj commented
> thanks! i would appreciate if you also remove the whitespace changes. after that is solved i think this can be merged

done!

2022-04-03 11:11 UTC, mifi commented on example.js
> -  maxLikesPerDay: 50,
Any reason why you changed the default from 50 to 30?

2022-04-03 11:27 UTC, mifi commented on Dockerfile
> +CMD ["yarn", "upgrade", "puppeteer:latest",  "instauto"]
Why is this line needed?

2023-02-26 12:54 UTC, thegreenmilecornant commented
Any news on this PR? Would love to use a simple docker compose to deploy instauto.

Tried building an image with the dockerfile (first time) - but failed.

2023-02-26 19:37 UTC, maxxxdj commented
> Any news on this PR? Would love to use a simple docker compose to deploy instauto.
> 
> Tried building an image with the dockerfile (first time) - but failed.

Hey!
I'm not sure why the owner didn't merged this one.
It was running fine on my side and even I had it with env variables so I can run different accounts.
If you copied that file and trying it on the current master maybe won't work, due to changes in master branch.

Try to ping mifi

2023-02-27 02:25 UTC, mifi commented
Hi. I left some code review questions that were not answered

2023-02-27 07:27 UTC, thegreenmilecornant commented
> Hey! I'm not sure why the owner didn't merged this one. It was running fine on my side and even I had it with env variables so I can run different accounts. If you copied that file and trying it on the current master maybe won't work, due to changes in master branch.
> 
> Try to ping mifi

OK. Would you be so kind and look at the requested changes by @mifi and update the PR 😃 ?
Would love to deploy this in Docker!

2023-03-04 09:37 UTC, mifi commented on docker-compose.yaml
> +      - USERS_TO_FOLLOW=users
```suggestion
      - USERS_TO_FOLLOW=everchanginghorizon,sam_kolder
```

2023-03-04 09:37 UTC, mifi commented on Dockerfile
> +
```suggestion
```

2023-03-04 09:37 UTC, mifi commented on Dockerfile
> +CMD ["yarn", "upgrade", "puppeteer:latest",  "instauto"]
```suggestion
CMD ["yarn"]
```

2023-03-04 09:38 UTC, mifi commented
if these changes look ok then we can merge

2023-03-04 12:28 UTC, mifi commented on example.js
> +        process.env.USERS_TO_FOLLOW.split(',');
```suggestion
    const usersToFollowFollowersOf = process.env.USERS_TO_FOLLOW != null ? process.env.USERS_TO_FOLLOW.split(',') : [];
```

2023-03-04 12:33 UTC, merged

2023-03-04 12:34 UTC, mifi commented
I haven't tested this but let me know if it doesnt work and we can do another PR to fix it